# Generated by Django 5.2.3 on 2025-06-16 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employees',
            name='hourlyrate',
            field=models.FloatField(),
        ),
    ]
