# Generated by Django 5.2.3 on 2025-07-07 13:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_employees_hourlyrate'),
    ]

    operations = [
        migrations.AddField(
            model_name='atandents',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.employees'),
        ),
    ]
