# Generated by Django 5.2.3 on 2025-07-07 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_atandents_employee'),
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=250)),
                ('art', models.CharField(max_length=250)),
                ('piz', models.IntegerField()),
                ('price', models.FloatField()),
                ('delivery_date', models.CharField(blank=True, max_length=250, null=True)),
                ('company_name', models.CharField(max_length=300)),
            ],
        ),
    ]
