# Generated by Django 5.2.3 on 2025-07-07 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_products'),
    ]

    operations = [
        migrations.CreateModel(
            name='Companies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('address', models.CharField(max_length=300)),
                ('phone_num', models.CharField(max_length=300)),
            ],
        ),
        migrations.AddField(
            model_name='products',
            name='delivery_completed_date',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='products',
            name='status',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
