# Generated by Django 5.2.3 on 2025-07-07 15:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_companies_products_delivery_completed_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='company_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.companies'),
        ),
    ]
