# Generated by Django 5.2.4 on 2025-07-16 23:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_products_company_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='delivery_completed_date',
        ),
        migrations.RemoveField(
            model_name='products',
            name='status',
        ),
        migrations.CreateModel(
            name='ProductDelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=250)),
                ('piz', models.CharField(max_length=250)),
                ('total_price', models.CharField(max_length=250)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.products')),
            ],
        ),
    ]
